const DiscountData = [
      {
        title: "Kadın",
        subtitles: [
          { subtitle: "Hepsini İncele", link: "#" },
          { subtitle: "Elbise", link: "#" },
          { subtitle: "Mayo", link: "#" },
          { subtitle: "Üst", link: "#" },
          { subtitle: "Gömlek & Bluz", link: "#" },
          { subtitle: "Pantolon", link: "#" },
          { subtitle: "Jean", link: "#" },
          { subtitle: "Şort", link: "#" },
          { subtitle: "Etek", link: "#" },
          { subtitle: "Blazer & Yelek", link: "#" },
          { subtitle: "Ceket & Kaban", link: "#" },
          { subtitle: "Hırka & Kazak", link: "#" },
          { subtitle: "Sweatshirt’ler & Kapüşonlular", link: "#" },
          { subtitle: "Tulum", link: "#" },
          { subtitle: "Aksesuar", link: "#" },
          { subtitle: "Ayakkabı", link: "#" },
          { subtitle: "İç Çamaşırı", link: "#" },
          { subtitle: "Gecelikler ve Ev Kıyafetleri", link: "#" },
          { subtitle: "Çorap & Külotlu Çorap", link: "#" },
          { subtitle: "Basic", link: "#" },
          { subtitle: "Hamile Giyim", link: "#" },
          { subtitle: "Büyük Beden", link: "#" },
          { subtitle: "Premium Selection", link: "#" },
          { subtitle: "Spor Giyim", link: "#" },
        ],
      },
      {
        title: "Divided",
        subtitles: [
          { subtitle: "Hepsini İncele", link: "#" },
          { subtitle: "Elbise", link: "#" },
          { subtitle: "Pantolon & Legging", link: "#" },
          { subtitle: "Jean'ler", link: "#" },
          { subtitle: "Şort", link: "#" },
          { subtitle: "Etekler", link: "#" },
          { subtitle: "Üst", link: "#" },
          { subtitle: "Gömlekler & Bluzlar", link: "#" },
          { subtitle: "Sweatshirt’ler & Kapüşonlular", link: "#" },
          { subtitle: "Ceket & Kaban", link: "#" },
          { subtitle: "Hırka & Kazak", link: "#" },
          { subtitle: "Basic", link: "#" },
          { subtitle: "Mayo", link: "#" },
          { subtitle: "Aksesuar", link: "#" },
          { subtitle: "Ayakkabı", link: "#" },
        ],
      },
      {
        title: "Erkek",
        subtitles: [
          { subtitle: "Hepsini İncele", link: "#" },
          { subtitle: "%30'dan başlayan indirim", link: "#" },
          { subtitle: "Tişört & Atlet", link: "#" },
          { subtitle: "Gömlek", link: "#" },
          { subtitle: "Şort", link: "#" },
          { subtitle: "Pantolon", link: "#" },
          { subtitle: "Jean", link: "#" },
          { subtitle: "İç giyim", link: "#" },
          { subtitle: "Mayo", link: "#" },
          { subtitle: "Sweatshirt’ler & Kapüşonlular", link: "#" },
          { subtitle: "Ceket ve Mont", link: "#" },
          { subtitle: "Blazer & Takım Elbise", link: "#" },
          { subtitle: "Hırka & Kazak", link: "#" },
          { subtitle: "Premium Selection", link: "#" },
          { subtitle: "Gecelikler ve Ev Kıyafetleri", link: "#" },
          { subtitle: "Aksesuar", link: "#" },
          { subtitle: "Çorap", link: "#" },
          { subtitle: "Spor Giyim", link: "#" },
          { subtitle: "Ayakkabı", link: "#" },
          { subtitle: "Basic", link: "#" },
          { subtitle: "Büyük Beden", link: "#" },
        ],
      },
      {
        title: "Çocuk",
        subtitles: [
          { subtitle: "Yeni eklenen stiller", link: "#" },
          { subtitle: "Tişörtler 39,99 TL’den itibaren", link: "#" },
          { subtitle: "Şort 59,99 TL’den itibaren", link: "#" },
          { subtitle: "%40 indirimden", link: "#" },
          { subtitle: "Kiz Çocuk 2-8 Yaş", link: "#" },
          { subtitle: "Erkek Çocuk 2-8 Yaş", link: "#" },
          { subtitle: "Kiz Çocuk 9-14 Yaş", link: "#" },
          { subtitle: "Erkek Çocuk 9-14 Yaş", link: "#" },
          { subtitle: "Tüm ürünleri göster", link: "#" },
          { subtitle: "NEW | Çocuklar için yeni koleksiyon", link: "#" },
        ],
      },
      {
        title: "Bebek",
        subtitles: [
          { subtitle: "Tüm ürünleri göster", link: "#" },
          { subtitle: "NEW | Bebekler için yeni koleksiyon", link: "#" },
        ],
      },
      {
        title: "Spor",
        subtitles: [
          { subtitle: "Hepsini incele", link: "#" },
          { subtitle: "Kadın", link: "#" },
          { subtitle: "Erkek", link: "#" },
          { subtitle: "Çocuk", link: "#" },
        ],
      },
      {
        title: "H&M HOME",
        subtitles: [
          { subtitle: "Hepsini İncele", link: "#" },
          { subtitle: "Yatak Odası", link: "#" },
          { subtitle: "Oturma Odası", link: "#" },
          { subtitle: "Çocuk Odası", link: "#" },
          { subtitle: "Mutfak", link: "#" },
          { subtitle: "Kırlent", link: "#" },
          { subtitle: "Depolama Çözümleri", link: "#" },
          { subtitle: "Dekorasyon", link: "#" },
          { subtitle: "Halı", link: "#" },
        ],
      },
    ];

export default DiscountData;